In [3]:
# what is linear algebra 

#### Define a symmertic 3x3 matric and print the transpose of the symmetric matrix

- This matrix is a 3x3 matrix because it has three rows and three columns

- transpose of a matrix means flipping a matrix over its diagonal, meaning switching the row and cloumn indices.
- formula: array.transpose(axes)
    - axes could be none , tuple of int or n ints
- properties of transpose= the transpose of the matrix is the matrix itself: (AT)=A. Transpose of a scalar multiple: The Transpoe of a matrix times a scalar(k) is equal to the consiant times the transpose of the matrix:(KA)
- transpose of a sum= the transpose of the sum of the two matrices is equvalent to the sum of their transposes= (A+)T=AT+BT
- Transpose of a product= the transpose of the product of two matrices is equivalent to the sum of their transposes= (A+B)T=AT+BT
- THE SAME IS TRUE FOR THE PRODUCT OF MULTIPLE MATRICES= (ABC)T=CTBTAT

#### Symmetric matrix
- symmetric matrix is a square matrix that is equal to its transpose 

In [1]:
a= np.array([[1,4,7],[4,3,6],[7,6,2]])
a

array([[1, 4, 7],
       [4, 3, 6],
       [7, 6, 2]])

In [2]:
a.transpose()

array([[1, 4, 7],
       [4, 3, 6],
       [7, 6, 2]])

#### with the 3x3 matrix calculate the 
- lower trangular matrix:
    - a square matrix with all elements above the diagonal 0 is a lower trangular matrix
    - the transpose of lwoer trangular matrix is upper trangular matrix
    - the inverse of a lower trangular matrix is lower trangular matrix
    - the product of two or more lower trangular matrix is also lower trangualr matrix
    
- upper trangular matrix :
    - a square matrix with all elements below the diagonal 0 is a upper trnagular matrix
    - the properties are similar to lower trangular matrix
    
    

In [9]:

lower_triangular_matrix = np.array([[1,0,0],[1,1,0],[1,1,1]])
print(lower_triangular_matrix)


[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [11]:
upper_triangular_matrix=lower_triangular_matrix.transpose()
print(upper_triangular_matrix)

[[1 1 1]
 [0 1 1]
 [0 0 1]]


#### define a 5x3 matrix and get the :
- diagonal vector
- get diagonal matrix form vector
    - diagonal matrix has all values 0 outside the diagonal(also known as scaling matrix)

In [12]:
a= np.arange(15).reshape(5,3)
print(a)
print(np.diag(a))
np.diag(np.diag(a))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[0 4 8]


array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

#### create a identity matrix
- a diagonal matrix with values 1 at its diagonals
- multiplying any matrix with identiry matrix results in the matrix itself
- the product of any two inverse matrices is always identiry matrix

In [14]:
a=np.identity(4, dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


#### define a orthogonal matrix and get:
- inverse of matrix
- show that  Q.QT=I 
- where Q is the orthogonal matrix

- a square matrix with real number or elements is said to be an orthogonal matrix.if its transpose is equal to its 
  inverse matrix or we can say, when the product of a square matrix and its transpose gives an identity matrix, 
    then the square matrix is known as an orthogonal matrix

In [ ]:
    q=np.array([[]])

#### Define a matrix and calulate the trace of matrix

- trace of matrix is the sum of its diagonal elements

In [15]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
np.trace(a)

12

#### define a 3x3 matrix and calc determinant, ie not invertable

- Determinant is a very useful value in linear algebra. It calculated from the diagonal elements
of a square matrix. For a 2x2 matrix, it is simply the subtraction of the product of the top left
and bottom right element from the product of other two.

- In other words, for a matrix [[a,b], [c,d]], the determinant is computed as ‘ad-bc’. 
The larger square matrices are considered to be a combination of 2x2 matrices.

In [29]:
x = np.arange(2,11).reshape(3,3)
print(x)
print (np.linalg.det(x))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
0.0


#### create a 2x2 matrix , 1x3 matrix and calculate the rank of the matrix

- the rank is how many of the rows/columns are unique(independant)
- rank is useful as it lets us know if we have chance of solving a system of linear equations: when 
    the rank equal the number of variable we many be able find the unique solution
    

In [31]:
data_1 = np.random.randint(10,size=(2,2))
print(data_1)
print(np.linalg.matrix_rank(data_1))

[[4 7]
 [2 2]]
2


In [36]:
one_three= np.random.randint(20,size=(1,3))
print(one_three)
print(np.linalg.matrix_rank(one_three))

[[ 1  6 15]]
1


#### create a 3*6 matrix with zeros and ones and count the zeros in matrix
- also find the size of matrix
- calculate the matrix sparsity: count of zeros / size of matrix

In [42]:
# np.eye= return a 2D array with ones on the diagonal and zeros elesehere
z = np.eye(3,6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [45]:
print(np.sum(z==0))
print(z.shape)

15
(3, 6)


- The number of zero-valued elements divided by the total number of elements (e.g., m × n for an m × n matrix) 
    is sometimes referred to as the sparsity of the matrix. Conceptually, sparsity corresponds to systems 
    with few pairwise interactions.

In [46]:
print("sparsity of the matrix")
print((np.sum(z==0))/np.prod(z.shape))

sparsity of the matrix
0.8333333333333334


#### convert the sparse using csr method and again reconstruct to dense
- A = array([ [1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0] ]) #dense matrix

In [48]:
from scipy import sparse
A= np.array([ [1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0] ])
print(sparse.csr_matrix(A))

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


#### define a tensor of matrix of shape(3,3,3)
- it is a multi-dimensiional array
- vector - 1 dimensional 
- matrix- 2 dimensional 
- if more than two dimensional , it is called tensor


In [1]:
G = np.arange(3*3*3).reshape(3,3,3)
print(G)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [3]:
G[:,:,0] # Column from the tensor

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

#### create a 2 tensor of size(3,3,3) and perform:
- tensor additon
- tensor substraction

In [9]:

F1 = G[:,:,0]
F2=G[:,:,-1]
G_reversed= G[::-1, ::-1, ::-1]
print(G_reversed)
print("-------")
print(G_reversed[1,0,:])



[[[26 25 24]
  [23 22 21]
  [20 19 18]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]
-------
[17 16 15]


In [11]:
Gsum= G + G_reversed
print(Gsum)
print("-------")
Gsubstr= G - G_reversed
print(Gsubstr)

[[[26 26 26]
  [26 26 26]
  [26 26 26]]

 [[26 26 26]
  [26 26 26]
  [26 26 26]]

 [[26 26 26]
  [26 26 26]
  [26 26 26]]]
-------
[[[-26 -24 -22]
  [-20 -18 -16]
  [-14 -12 -10]]

 [[ -8  -6  -4]
  [ -2   0   2]
  [  4   6   8]]

 [[ 10  12  14]
  [ 16  18  20]
  [ 22  24  26]]]


In [ ]:
#### perfrom a Hadamard product for the above tensor 

In [13]:
Ghadamard = G * G_reversed
print(Ghadamard)

[[[  0  25  48]
  [ 69  88 105]
  [120 133 144]]

 [[153 160 165]
  [168 169 168]
  [165 160 153]]

 [[144 133 120]
  [105  88  69]
  [ 48  25   0]]]


In [14]:
Gh = np.multiply(G,G_reversed)
print(Gh)

[[[  0  25  48]
  [ 69  88 105]
  [120 133 144]]

 [[153 160 165]
  [168 169 168]
  [165 160 153]]

 [[144 133 120]
  [105  88  69]
  [ 48  25   0]]]


#### Perform a Tensor division for a tensor of shape T1 and T2 of shape(4,3,3)

In [17]:
K = np.arange(4*3*3).reshape(4,3,3)
print(K)
L = np.random.randint(1,36,(4,3,3))
M1= np.divide(K,L)
print("-------")
M2 = K/L
print(M2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]
-------
[[[ 0.          0.04761905  0.08333333]
  [ 1.5         0.18181818  1.25      ]
  [ 0.20689655  0.25925926  1.6       ]]

 [[ 0.47368421  5.          0.40740741]
  [ 0.8         2.16666667  0.4516129 ]
  [ 0.42857143  1.45454545  1.13333333]]

 [[ 0.54545455  0.61290323  1.05263158]
  [21.          1.46666667  1.04545455]
  [ 0.92307692  1.04166667  1.23809524]]

 [[ 0.77142857  1.47368421  1.        ]
  [ 1.2        10.33333333  4.        ]
  [ 5.5         2.26666667  1.34615385]]]


#### define a 2 tensor of 2x2 and calculate the tensor product

In [21]:
N= np.arange(2*2).reshape(2,2)
P= np.random.randint(1,11,(2,2))
Np= np.tensordot(N,P, axes=0)
print(Np)

[[[[ 0  0]
   [ 0  0]]

  [[ 8 10]
   [ 5  8]]]


 [[[16 20]
   [10 16]]

  [[24 30]
   [15 24]]]]


In [23]:
Nprod=np.dot(N,P)
print(Nprod)

[[ 5  8]
 [31 44]]


In [24]:
print(np.kron(N,P))

[[ 0  0  8 10]
 [ 0  0  5  8]
 [16 20 24 30]
 [10 16 15 24]]


#### calulate the factorization factors a matrix(Lu) decompostion for an array of shape 3x3

In [27]:

from scipy import linalg

S= np.random.randint(0,10,(3,3))
print(S)
S1= scipy.linalg

[[6 7 7]
 [8 7 5]
 [8 0 4]]


NameError: name 'scipy' is not defined

- what is lu decomposition ?
    -  LU stands for 'Lower Upper', and so an LU decomposition of a matrix A is a decomposition so that.
    A=LU. where L is lower triangular and U is upper triangular. Now, LU decomposition is 
    essentially gaussian elimination, but we work only with the matrix A (as opposed to the augmented matrix


#### from a matrix of shape 3x2
- calculate the QR decompostion
- reconstruct the original matrix 

#### Define a 3x3 matrix calculate:
- cholesky decomposition using lower factorize
- reconstruct the original matrix

#### define a 3x3 matrix and calculate the:
- eigendecomposition
    - it is also called sepcial decomposition
    - applicale for square matrix. A with linearly independent eigenvectors(not necessarily distince eigenvalues)
   -  A=V D V^{-1}

In [54]:
A = np.array([[1,0,0], [-1,2,1,5],[0,0,-1]])
D, V = np.linalg.eig(A)
print("eigenvalues: ", D)
print("eigenvector: ")
print(V)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

#### from the above eigendecomposition conform an eigenvector and eigenvalue

#### Reconstruct the matrix from the Eigendecompostion

#### calculate the L1 norm for a 1x3 matrix

In [ ]:
- 

In [50]:
mat= np.arange(3).reshape(1,3)
print(mat)
np.linalg.norm(mat,1)

[[0 1 2]]


2.0

#### calculate the L2 norm for the 1x4 matrix
- L2 form 
    - also known as Eucidean norm. it is the shortes distance to go from one point to another. 



In [55]:
x = np.array([2,6,5,4])
np.linalg.norm(x,ord=2)


9.0

In [57]:
a= np.array([[1,2],[3,4]])
print(a)
np.linalg.norm(a, ord=2)

[[1 2]
 [3 4]]


5.464985704219043